config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  post "income_values/new(/:name)" => "income_values#new"
  post "fixedcost_values/new(/:name)" => "fixedcost_values#new"
  post "variablecost_values/new(/:name)" => "variablecost_values#new"

  resources :incomes
  resources :fixedcosts
  resources :variablecosts
  resources :income_values
  resources :fixedcost_values
  resources :variablecost_values
end

app/models/fixedcost_value.rb
class FixedcostValue < ApplicationRecord
  validates :value, presence: true
end

app/models/form/fixedcost_value.rb
class Form::FixedcostValue < FixedcostValue
	REGISTRABLE_ATTRIBUTES = %i(fixedcost_id year_month value description)
	attr_accessor :fixedcost_id
	attr_accessor :year_month
	attr_accessor :value
	attr_accessor :description
end

app/controllers/fixedcost_values_controller.rb
class FixedcostValuesController < ApplicationController
	before_action :set_fixedcostvalue, only: [:show, :edit, :update, :destroy]

  def index
		@fixedcosts = Fixedcost.order(:created_at)
		@fixedcost_values = FixedcostValue.order(:year_month)
	end
 
	def show
	end
 
	def new
		year_month_day = params[:year_month] + "-01"
		@year_month = year_month_day.to_date
 
		@fixedcosts = Fixedcost.order(:created_at)
		@form = Form::FixedcostForm.new
	end
 
	def edit
		@fixedcost = Fixedcost.find(@fixedcost_value.fixedcost_id)
	end
 
	def create
		@form = Form::FixedcostForm.new(fixedcost_form_params)
		if @form.save
			redirect_to :fixedcost_values, notice: "登録しました"
		else
			redirect_to :fixedcost_values, notice: "登録に失敗しました"
		end
	end
 
	def fixedcost_form_params
		params
			.require(:form_fixedcost_form)
			.permit(fixedcost_values_attributes: Form::FixedcostValue::REGISTRABLE_ATTRIBUTES)
	end
 
	def update
		@fixedcost_value.assign_attributes(params[:fixedcost_value])
		if @fixedcost_value.save
			redirect_to :fixedcost_values, notice: "情報を更新しました"
		else
			render "edit"
		end
	end
 
	def destroy
		@fixedcost_value.destroy
		redirect_to :fixedcost_values, notice: "データを削除しました"
	end

	private
	def set_fixedcostvalue
		@fixedcost_value = FixedcostValue.find(params[:id])
	end
end

app/helpers/fixedcost_values_helper.rb
module FixedcostValuesHelper
end

app/views/fixedcost_values/edit.html.erb
<h2>固定費科目 データ修正 </h2>
 
<%= form_for @fixedcost_value do |form| %>
<table>
	<tr>
		<th>登録日</th>
		<th>名称</th>
		<th>値</th>
		<th>備考</th>
	</tr>
 
	<tr>
		<td><%= form.date_select :year_month,
	 				start_year: 2010, end_year: Time.current.year,
	 				use_month_numbers: true, discard_day: true %></td>
		<th><%= @fixedcost.name %></th>
	 	<td><%= form.text_field :value %></td>
	 	<td><%= form.text_field :description %></td>
	</tr>
</table>
<div><%= form.submit %></div>
<% end %>

app/views/fixedcost_values/index.html.erb
<% require 'active_support/core_ext/numeric/conversions' %>
<h2>固定費科目のデータ登録</h2>
<p>登録年月を設定してください</p>
<%= form_tag({controller: :fixedcost_values, action: :new}, {method: :post}) do %>
	<input type="month" name="year_month">
	<input type="submit", class="btn btn--orange btn--radius">
<% end %>
 
<h2>固定費科目 データ一覧 </h2>
<% if @fixedcost_values.present? %>
<table>
  <tr>
    <th>登録年月</th>
    <th>名称</th>
    <th>値</th>
    <th>備考</th>
		<th>操作</th>
  </tr>
	<% @fixedcost_values.each do |fixedcost_value| %>
	<tr>
		<td><%= fixedcost_value.year_month.strftime('%Y年%m月') %></td>
		<td><%= @fixedcosts.find(fixedcost_value.fixedcost_id).name %></td>
		<td><%= fixedcost_value.value.to_s(:delimited) %> 円</td>
		<td><%= fixedcost_value.description %></td>
		<td>
		<%= link_to "編集", [:edit, fixedcost_value] %> |
		<%= link_to "削除", fixedcost_value, method: :delete,
			data: { confirm: "本当に削除しますか？"} %>
		</td>
	</tr>
	<% end %>
</table>
<% else %>
	<p>登録されているデータがありません。</p>
<% end %>

app/views/fixedcost_values/new.html.erb
<% @page_title = "固定費科目 データ登録" %>
<h2><%= @page_title %></h2>
<div class="toolbar"><%= link_to "固定費科目データ一覧に戻る", :fixedcost_values %></div>
<%= form_for(@form, url: fixedcost_values_path, method: :post) do |fb| %>
 
<!-- 年月テーブル -->
<table>
  <tr>
    <th>登録年月</th>
    <th>名称</th>
    <th>値</th>
    <th>備考</th>
  </tr>
 
  <% cnt=0 %>
  <%= fb.fields_for :fixedcost_values do |f| %>
  <%= f.hidden_field :fixedcost_id %>
 
 <tr>
		<td>
      <%= f.date_select :year_month,
						start_year: 2010, end_year: Time.current.year,
						use_month_numbers: true, discard_day: true, default: @year_month
            %>
    </td>
 
   <th>
    <%= @fixedcosts.find(@form.fixedcost_values[cnt].fixedcost_id).name %>
    </th>
    <td><%= f.text_field :value, size: 8 %>円</td>
    <td><%= f.text_field :description, size: 8 %></td>
    <% cnt+=1 %>
 </tr>
<% end %>
</table>
 
<div><input type="submit", class="btn btn--orange btn--radius"></div>
<% end %>