config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  post "income_values/new(/:name)" => "income_values#new"
  post "fixedcost_values/new(/:name)" => "fixedcost_values#new"
  post "variablecost_values/new(/:name)" => "variablecost_values#new"

  resources :incomes
  resources :fixedcosts
  resources :variablecosts
  resources :income_values
  resources :fixedcost_values
  resources :variablecost_values
end

app/models/form/variablecost_value.rb
class Form::VariablecostValue < VariablecostValue
	REGISTRABLE_ATTRIBUTES = %i(variablecost_id year_month value description)
	attr_accessor :variablecost_id
	attr_accessor :year_month
	attr_accessor :value
	attr_accessor :description
end

app/models/variablecost_value.rb
class VariablecostValue < ApplicationRecord
  validates :value, presence: true
end

app/controllers/variablecost_values_controller.rb
class VariablecostValuesController < ApplicationController
  before_action :set_fixedcostvalue, only: [:show, :edit, :update, :destroy]

  def index
		@variablecosts = Variablecost.order(:created_at)
		@variablecost_values = VariablecostValue.order(:year_month)
	end
 
	def show
	end
 
	def new
		year_month_day = params[:year_month] + "-01"
		@year_month = year_month_day.to_date
 
		@variablecosts = Variablecost.order(:created_at)
		@form = Form::VariablecostForm.new
	end
 
	def edit
		@variablecost = Variablecost.find(@variablecost_value.variablecost_id)
	end
 
	def create
		@form = Form::VariablecostForm.new(variablecost_form_params)
		if @form.save
			redirect_to :variablecost_values, notice: "登録しました"
		else
			redirect_to :variablecost_values, notice: "登録に失敗しました"
		end
	end
 
	def variablecost_form_params
		params
			.require(:form_variablecost_form)
			.permit(variablecost_values_attributes: Form::VariablecostValue::REGISTRABLE_ATTRIBUTES)
	end
 
	def update
		@variablecost_value.assign_attributes(params[:variablecost_value])
		if @variablecost_value.save
			redirect_to :variablecost_values, notice: "情報を更新しました"
		else
			render "edit"
		end
	end
 
	def destroy
		@variablecost_value.destroy
		redirect_to :variablecost_values, notice: "データを削除しました"
	end

  private
  def set_variablecostvalue
		@variablecost_value = VariablecostValue.find(params[:id])
  end
end

app/helpers/variablecost_values_helper.rb
module VariablecostValuesHelper
end

app/views/variablecost_values/edit.html.erb
<h2>変動費科目 データ修正 </h2>
<%= form_for @variablecost_value do |form| %>
<table>
	<tr>
		<th>登録日</th>
		<th>名称</th>
		<th>値</th>
		<th>備考</th>
	</tr>

	<tr>
		<td><%= form.date_select :year_month,
	 				start_year: 2010, end_year: Time.current.year,
	 				use_month_numbers: true, discard_day: true %></td>
		<th><%= @variablecost.name %></th>
	 	<td><%= form.text_field :value %></td>
	 	<td><%= form.text_field :description %></td>
	</tr>
</table>
<div><%= form.submit %></div>
<% end %>

app/views/variablecost_values/index.html.erb
<% require 'active_support/core_ext/numeric/conversions' %>
 
<h2>変動費科目のデータ登録</h2>
<p>登録年月を設定してください</p>
<%= form_tag({controller: :variablecost_values, action: :new}, {method: :post}) do %>
	<input type="month" name="year_month">
	<input type="submit", class="btn btn--orange btn--radius">
<% end %>
 
 
<h2>変動費科目 データ一覧 </h2>
 
<% if @variablecost_values.present? %>
<table>
  <tr>
    <th>登録年月</th>
    <th>名称</th>
    <th>値</th>
    <th>備考</th>
		<th>操作</th>
  </tr>
	<% @variablecost_values.each do |variablecost_value| %>
	<tr>
		<td><%= variablecost_value.year_month.strftime('%Y年%m月') %></td>
		<td><%= @variablecosts.find(variablecost_value.variablecost_id).name %></td>
		<td><%= variablecost_value.value.to_s(:delimited) %> 円</td>
		<td><%= variablecost_value.description %></td>
		<td>
		<%= link_to "編集", [:edit, variablecost_value] %> |
		<%= link_to "削除", variablecost_value, method: :delete,
			data: { confirm: "本当に削除しますか？"} %>
		</td>
	</tr>
	<% end %>
</table>
<% else %>
	<p>登録されているデータがありません。</p>
<% end %>

app/views/variablecost_values/new.html.erb
<% @page_title = "変動費科目 データ登録" %>
<h2><%= @page_title %></h2>
<div class="toolbar"><%= link_to "変動費科目データ一覧に戻る", :variablecost_values %></div>
<%= form_for(@form, url: variablecost_values_path, method: :post) do |fb| %>
 
<!-- 年月テーブル -->
<table>
  <tr>
    <th>登録年月</th>
    <th>名称</th>
    <th>値</th>
    <th>備考</th>
  </tr>
 
  <% cnt=0 %>
  <%= fb.fields_for :variablecost_values do |f| %>
  <%= f.hidden_field :variablecost_id %>
 
 <tr>
		<td>
      <%= f.date_select :year_month,
						start_year: 2010, end_year: Time.current.year,
						use_month_numbers: true, discard_day: true, default: @year_month
            %>
    </td>
 
   <th>
    <%= @variablecosts.find(@form.variablecost_values[cnt].variablecost_id).name %>
    </th>
    <% cnt+=1 %>
    <td><%= f.text_field :value, size: 8 %></td>
    <td><%= f.text_field :description, size: 8 %></td>
 
 </tr>
<% end %>
</table>
 
<div><input type="submit", class="btn btn--orange btn--radius"></div>
<% end %>